channels:
- https://packages.qiime2.org/qiime2/2025.4/tiny/passed
- conda-forge
- bioconda
dependencies:
- biom-format=2.1.15
- h5py=3.11.0
- hdf5=1.14.3
- notebook=6.5.5
- numpy=1.26.4
- pandas=2.2.2
- parsl=2024.4.15
- python=3.10
- q2-metadata=2025.4.0.dev0+1.gb14bd3a
- q2-mystery-stew=2025.4.0.dev0+1.g2c304d4
- q2-types=2025.4.0.dev0+1.g56787c0
- q2cli=2025.4.0.dev0+5.gbaec1d1
- q2templates=2025.4.0.dev0+2.gf05d0b1
- qiime2=2025.4.0.dev0+8.ged7a2db
- r-base=4.3.3
- r-reticulate=1.36.0
- scikit-bio=0.6.0
- scikit-learn=1.4.2
- scipy=1.13.0
- unifrac-binaries=1.4
- unifrac=1.3
extras:
  variant_override:
    qiime2_epoch: '2025.4'
# modified: 2025-01-05
