name: Add New Workflow to Amplicon Repos

on:
  workflow_dispatch:
    inputs:
      # The path to the workflow file under distributions
      workflow_file_path:
        description: "Path to the workflow file to distribute (under distributions)"
        required: true
        default: ".github/workflows/my-new-workflow.yaml"

jobs:
  add-workflow-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install yq for YAML parsing
        # Using mikefarah/yq binary
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          sudo wget https://github.com/mikefarah/yq/releases/download/v4.35.1/yq_linux_amd64 -O /usr/local/bin/yq
          sudo chmod +x /usr/local/bin/yq

      - name: Parse data.yaml to find amplicon repos
        id: parse_repos
        run: |
          REPOSITORIES=$(yq '.packages[]
            | select(.distros[] == "amplicon")
            | .repo' data.yaml | paste -sd " " -)

          echo "Found these amplicon repos: $REPOSITORIES"
          echo "repositories=$REPOSITORIES" >> $GITHUB_OUTPUT

      - name: Configure Git
        run: |
          git config --global user.name "q2d2"
          git config --global user.email "q2d2.noreply@gmail.com"

      - name: Distribute the workflow file
        env:
          REPOSITORIES: ${{ steps.parse_repos.outputs.repositories }}
          REPO_PUSH_TOKEN: ${{ secrets.BOT_PAT }}
          WORKFLOW_FILE_PATH: ${{ github.event.inputs.workflow_file_path }}
        run: |
          TARGET_BRANCH="add-custom-workflow"

          echo "Will distribute '${WORKFLOW_FILE_PATH}' to these repositories:"
          echo "${REPOSITORIES}"

          for REPO in $REPOSITORIES; do
            echo "Processing $REPO..."

            git clone --depth 1 https://x-access-token:${REPO_PUSH_TOKEN}@github.com/$REPO
            cd "$(basename "$REPO")"

            git checkout -b "$TARGET_BRANCH" || git checkout "$TARGET_BRANCH"

            mkdir -p .github/workflows

            cp "../${WORKFLOW_FILE_PATH}" ".github/workflows/$(basename "$WORKFLOW_FILE_PATH")"

            git add ".github/workflows/$(basename "$WORKFLOW_FILE_PATH")"
            git commit -m "Add designated workflow file ($(basename "$WORKFLOW_FILE_PATH"))"
            git push origin "$TARGET_BRANCH"

            cd ..
            rm -rf "$(basename "$REPO")"
          done
