name: cron-prepare
on:
  workflow_dispatch: {}
  schedule:
    - cron: 0 0 * * SUN

jobs:
  tiny:
    uses: ./.github/workflows/create-prepare-pr.yaml
    secrets: inherit
    with:
      distro: tiny

  amplicon:
    needs: [tiny]
    uses: ./.github/workflows/create-prepare-pr.yaml
    secrets: inherit
    with:
      distro: amplicon

  moshpit:
    needs: [tiny, amplicon]
    uses: ./.github/workflows/create-prepare-pr.yaml
    secrets: inherit
    with:
      distro: moshpit

  pathogenome:
    needs: [tiny, amplicon, moshpit]
    uses: ./.github/workflows/create-prepare-pr.yaml
    secrets: inherit
    with:
      distro: pathogenome
