# # Example of workflow trigger for calling workflow (the client).
# name: ci-vizard
# on:
#   pull_request:
#     branches: ["dev"]
#   push:
#     branches: ["dev"]
# jobs:
#   ci:
#     uses: qiime2/distributions/.github/workflows/lib-community-ci.yaml@dev
#     with:
#       github-repo: q2-vizard
#       env-file-name: 2024.5-vizard-environment.yml

on:
  workflow_call:
    inputs:
      github-repo:
        description: "Plugin repository name on Github"
        type: string
        required: true

      env-file-name:
        description: "Name of environment file to test with"
        type: string
        required: true

env:
  name: ${{ inputs.github-repo }}
  filepath: environment-files/${{ inputs.env-file-name }}

jobs:
  install-env-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: 'checkout source'
        uses: actions/checkout@v4

      - name: 'set up python 3.9'
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: 'set up conda environment'
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: 'latest'
          architecture: 'x64'
          environment-file: ${{ env.filepath }}
          activate-environment: ${{ env.name }}

      - name: 'Install package locally and run tests for ${{ env.name }}'
        shell: bash -el {0}
        run: |
          make dev
          conda install pytest
          qiime info
          pytest
